// <auto-generated />
using System;
using Mailer_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mailer_API.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20190226170703_initialmigrationscript")]
    partial class initialmigrationscript
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mailer_API.Models.DraftMailTable", b =>
                {
                    b.Property<long>("draft_mail_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("mail_body")
                        .HasMaxLength(5000);

                    b.Property<string>("mail_from")
                        .HasMaxLength(80);

                    b.Property<string>("mail_subject")
                        .HasMaxLength(100);

                    b.HasKey("draft_mail_ID");

                    b.ToTable("draft_mail_table");
                });

            modelBuilder.Entity("Mailer_API.Models.MailTable", b =>
                {
                    b.Property<long>("mail_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("attachment_1")
                        .HasMaxLength(100);

                    b.Property<string>("attachment_2")
                        .HasMaxLength(100);

                    b.Property<string>("attachment_3")
                        .HasMaxLength(100);

                    b.Property<string>("attachment_4")
                        .HasMaxLength(100);

                    b.Property<string>("attachment_5")
                        .HasMaxLength(100);

                    b.Property<int>("is_important");

                    b.Property<int>("is_starred");

                    b.Property<string>("mail_body")
                        .HasMaxLength(5000);

                    b.Property<DateTime>("mail_date");

                    b.Property<string>("mail_from")
                        .HasMaxLength(80);

                    b.Property<string>("mail_status");

                    b.Property<string>("mail_subject")
                        .HasMaxLength(100);

                    b.Property<string>("mail_to_1")
                        .HasMaxLength(80);

                    b.Property<string>("mail_to_2")
                        .HasMaxLength(80);

                    b.Property<string>("mail_to_3")
                        .HasMaxLength(80);

                    b.Property<string>("mail_to_4")
                        .HasMaxLength(80);

                    b.Property<string>("mail_to_5")
                        .HasMaxLength(80);

                    b.Property<string>("receiver_delete_status");

                    b.Property<string>("sender_delete_status");

                    b.HasKey("mail_ID");

                    b.ToTable("mail_table");
                });

            modelBuilder.Entity("Mailer_API.Models.UserTable", b =>
                {
                    b.Property<long>("user_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("first_name")
                        .HasMaxLength(20);

                    b.Property<string>("password")
                        .HasMaxLength(16);

                    b.Property<string>("phone_number")
                        .HasMaxLength(10);

                    b.Property<string>("second_name")
                        .HasMaxLength(20);

                    b.Property<string>("username")
                        .HasMaxLength(20);

                    b.HasKey("user_ID");

                    b.ToTable("user_table");
                });
#pragma warning restore 612, 618
        }
    }
}
